id: P006867
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17056
  title: ལམ་རིམ་དམིགས་རིམ་མདོར་བསྡུས།
  author: ''
  volumes:
    fcb12770525a4cc38c37697a4fd953cf:
      image_group_id: I8LS17062
      title: ''
      volume_number: 1
      total_pages: 30
      base_file: v001.txt
