id: P006867
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:27:31.320071
source_metadata:
  id: bdr:W8LS17056
  title: ལམ་རིམ་དམིགས་རིམ་མདོར་བསྡུས།
  author: ''
  volumes:
    fcb12770525a4cc38c37697a4fd953cf:
      image_group_id: I8LS17062
      title: ''
      volume_number: 1
      total_pages: 30
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
